/*
 * Copyright © 2011 Everit Kft. (http://www.everit.org)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Service Desk Public REST API
 * Public REST API for Jira Service Desk
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.everit.atlassian.restclient.servicedeskcloud.v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.ContentDTO;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.SourceDTO;

/**
 * ArticleDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-02T14:33:08.600+02:00[Europe/Prague]")
public class ArticleDTO {
  @JsonProperty("title")
  private String title;

  @JsonProperty("excerpt")
  private String excerpt;

  @JsonProperty("source")
  private SourceDTO source;

  @JsonProperty("content")
  private ContentDTO content;

  public ArticleDTO title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Title of the article.
   * @return title
  **/
  @ApiModelProperty(value = "Title of the article.")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public ArticleDTO excerpt(String excerpt) {
    this.excerpt = excerpt;
    return this;
  }

   /**
   * Excerpt of the article which matches the given query string.
   * @return excerpt
  **/
  @ApiModelProperty(value = "Excerpt of the article which matches the given query string.")
  public String getExcerpt() {
    return excerpt;
  }

  public void setExcerpt(String excerpt) {
    this.excerpt = excerpt;
  }

  public ArticleDTO source(SourceDTO source) {
    this.source = source;
    return this;
  }

   /**
   * Source of the article.
   * @return source
  **/
  @ApiModelProperty(value = "Source of the article.")
  public SourceDTO getSource() {
    return source;
  }

  public void setSource(SourceDTO source) {
    this.source = source;
  }

  public ArticleDTO content(ContentDTO content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @ApiModelProperty(value = "")
  public ContentDTO getContent() {
    return content;
  }

  public void setContent(ContentDTO content) {
    this.content = content;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArticleDTO articleDTO = (ArticleDTO) o;
    return Objects.equals(this.title, articleDTO.title) &&
        Objects.equals(this.excerpt, articleDTO.excerpt) &&
        Objects.equals(this.source, articleDTO.source) &&
        Objects.equals(this.content, articleDTO.content);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, excerpt, source, content);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArticleDTO {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    excerpt: ").append(toIndentedString(excerpt)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

