/*
 * Copyright © 2011 Everit Kft. (http://www.everit.org)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Service Desk Public REST API
 * Public REST API for Jira Service Desk
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.everit.atlassian.restclient.servicedeskcloud.v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.CommentDTO;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.PagedDTOAttachmentDTO;

/**
 * AttachmentCreateResultDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-02T14:33:08.600+02:00[Europe/Prague]")
public class AttachmentCreateResultDTO {
  @JsonProperty("comment")
  private CommentDTO comment;

  @JsonProperty("attachments")
  private PagedDTOAttachmentDTO attachments;

  public AttachmentCreateResultDTO comment(CommentDTO comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Details of the comment included with the attachments.
   * @return comment
  **/
  @ApiModelProperty(value = "Details of the comment included with the attachments.")
  public CommentDTO getComment() {
    return comment;
  }

  public void setComment(CommentDTO comment) {
    this.comment = comment;
  }

  public AttachmentCreateResultDTO attachments(PagedDTOAttachmentDTO attachments) {
    this.attachments = attachments;
    return this;
  }

   /**
   * List of the attachments added.
   * @return attachments
  **/
  @ApiModelProperty(value = "List of the attachments added.")
  public PagedDTOAttachmentDTO getAttachments() {
    return attachments;
  }

  public void setAttachments(PagedDTOAttachmentDTO attachments) {
    this.attachments = attachments;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttachmentCreateResultDTO attachmentCreateResultDTO = (AttachmentCreateResultDTO) o;
    return Objects.equals(this.comment, attachmentCreateResultDTO.comment) &&
        Objects.equals(this.attachments, attachmentCreateResultDTO.attachments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(comment, attachments);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttachmentCreateResultDTO {\n");
    
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

