/*
 * Copyright © 2011 Everit Kft. (http://www.everit.org)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Service Desk Public REST API
 * Public REST API for Jira Service Desk
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.everit.atlassian.restclient.servicedeskcloud.v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.AdditionalCommentDTO;

/**
 * AttachmentCreateDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-02T14:33:08.600+02:00[Europe/Prague]")
public class AttachmentCreateDTO {
  @JsonProperty("temporaryAttachmentIds")
  private List<String> temporaryAttachmentIds = new ArrayList<>();

  @JsonProperty("additionalComment")
  private AdditionalCommentDTO additionalComment;

  @JsonProperty("public")
  private Boolean _public;

  public AttachmentCreateDTO temporaryAttachmentIds(List<String> temporaryAttachmentIds) {
    this.temporaryAttachmentIds = temporaryAttachmentIds;
    return this;
  }

  public AttachmentCreateDTO addTemporaryAttachmentIdsItem(String temporaryAttachmentIdsItem) {
    if (this.temporaryAttachmentIds == null) {
      this.temporaryAttachmentIds = new ArrayList<>();
    }
    this.temporaryAttachmentIds.add(temporaryAttachmentIdsItem);
    return this;
  }

   /**
   * List of IDs for the temporary attachments to be added to the customer request.
   * @return temporaryAttachmentIds
  **/
  @ApiModelProperty(value = "List of IDs for the temporary attachments to be added to the customer request.")
  public List<String> getTemporaryAttachmentIds() {
    return temporaryAttachmentIds;
  }

  public void setTemporaryAttachmentIds(List<String> temporaryAttachmentIds) {
    this.temporaryAttachmentIds = temporaryAttachmentIds;
  }

  public AttachmentCreateDTO additionalComment(AdditionalCommentDTO additionalComment) {
    this.additionalComment = additionalComment;
    return this;
  }

   /**
   * Comment about the attachments.
   * @return additionalComment
  **/
  @ApiModelProperty(value = "Comment about the attachments.")
  public AdditionalCommentDTO getAdditionalComment() {
    return additionalComment;
  }

  public void setAdditionalComment(AdditionalCommentDTO additionalComment) {
    this.additionalComment = additionalComment;
  }

  public AttachmentCreateDTO _public(Boolean _public) {
    this._public = _public;
    return this;
  }

   /**
   * Indicates whether the attachments are to be public (true) or private/internal (false).
   * @return _public
  **/
  @ApiModelProperty(value = "Indicates whether the attachments are to be public (true) or private/internal (false).")
  public Boolean getPublic() {
    return _public;
  }

  public void setPublic(Boolean _public) {
    this._public = _public;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttachmentCreateDTO attachmentCreateDTO = (AttachmentCreateDTO) o;
    return Objects.equals(this.temporaryAttachmentIds, attachmentCreateDTO.temporaryAttachmentIds) &&
        Objects.equals(this.additionalComment, attachmentCreateDTO.additionalComment) &&
        Objects.equals(this._public, attachmentCreateDTO._public);
  }

  @Override
  public int hashCode() {
    return Objects.hash(temporaryAttachmentIds, additionalComment, _public);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttachmentCreateDTO {\n");
    
    sb.append("    temporaryAttachmentIds: ").append(toIndentedString(temporaryAttachmentIds)).append("\n");
    sb.append("    additionalComment: ").append(toIndentedString(additionalComment)).append("\n");
    sb.append("    _public: ").append(toIndentedString(_public)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

