/*
 * Copyright © 2011 Everit Kft. (http://www.everit.org)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Service Desk Public REST API
 * Public REST API for Jira Service Desk
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.everit.atlassian.restclient.servicedeskcloud.v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * CustomerRequestFieldValueDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-02T14:33:08.600+02:00[Europe/Prague]")
public class CustomerRequestFieldValueDTO {
  @JsonProperty("fieldId")
  private String fieldId;

  @JsonProperty("label")
  private String label;

  @JsonProperty("value")
  private Object value = null;

  @JsonProperty("renderedValue")
  private Object renderedValue = null;

  public CustomerRequestFieldValueDTO fieldId(String fieldId) {
    this.fieldId = fieldId;
    return this;
  }

   /**
   * ID of the field.
   * @return fieldId
  **/
  @ApiModelProperty(value = "ID of the field.")
  public String getFieldId() {
    return fieldId;
  }

  public void setFieldId(String fieldId) {
    this.fieldId = fieldId;
  }

  public CustomerRequestFieldValueDTO label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Text label for the field.
   * @return label
  **/
  @ApiModelProperty(value = "Text label for the field.")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public CustomerRequestFieldValueDTO value(Object value) {
    this.value = value;
    return this;
  }

   /**
   * Value of the field.
   * @return value
  **/
  @ApiModelProperty(value = "Value of the field.")
  public Object getValue() {
    return value;
  }

  public void setValue(Object value) {
    this.value = value;
  }

  public CustomerRequestFieldValueDTO renderedValue(Object renderedValue) {
    this.renderedValue = renderedValue;
    return this;
  }

   /**
   * Value of the field rendered in the UI.
   * @return renderedValue
  **/
  @ApiModelProperty(value = "Value of the field rendered in the UI.")
  public Object getRenderedValue() {
    return renderedValue;
  }

  public void setRenderedValue(Object renderedValue) {
    this.renderedValue = renderedValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerRequestFieldValueDTO customerRequestFieldValueDTO = (CustomerRequestFieldValueDTO) o;
    return Objects.equals(this.fieldId, customerRequestFieldValueDTO.fieldId) &&
        Objects.equals(this.label, customerRequestFieldValueDTO.label) &&
        Objects.equals(this.value, customerRequestFieldValueDTO.value) &&
        Objects.equals(this.renderedValue, customerRequestFieldValueDTO.renderedValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fieldId, label, value, renderedValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerRequestFieldValueDTO {\n");
    
    sb.append("    fieldId: ").append(toIndentedString(fieldId)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    renderedValue: ").append(toIndentedString(renderedValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

