/*
 * Copyright © 2011 Everit Kft. (http://www.everit.org)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Service Desk Public REST API
 * Public REST API for Jira Service Desk
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.everit.atlassian.restclient.servicedeskcloud.v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.RequestTypeFieldDTO;

/**
 * CustomerRequestCreateMetaDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-02T14:33:08.600+02:00[Europe/Prague]")
public class CustomerRequestCreateMetaDTO {
  @JsonProperty("requestTypeFields")
  private List<RequestTypeFieldDTO> requestTypeFields = new ArrayList<>();

  @JsonProperty("canRaiseOnBehalfOf")
  private Boolean canRaiseOnBehalfOf;

  @JsonProperty("canAddRequestParticipants")
  private Boolean canAddRequestParticipants;

  public CustomerRequestCreateMetaDTO requestTypeFields(List<RequestTypeFieldDTO> requestTypeFields) {
    this.requestTypeFields = requestTypeFields;
    return this;
  }

  public CustomerRequestCreateMetaDTO addRequestTypeFieldsItem(RequestTypeFieldDTO requestTypeFieldsItem) {
    if (this.requestTypeFields == null) {
      this.requestTypeFields = new ArrayList<>();
    }
    this.requestTypeFields.add(requestTypeFieldsItem);
    return this;
  }

   /**
   * List of the fields included in this request.
   * @return requestTypeFields
  **/
  @ApiModelProperty(value = "List of the fields included in this request.")
  public List<RequestTypeFieldDTO> getRequestTypeFields() {
    return requestTypeFields;
  }

  public void setRequestTypeFields(List<RequestTypeFieldDTO> requestTypeFields) {
    this.requestTypeFields = requestTypeFields;
  }

  public CustomerRequestCreateMetaDTO canRaiseOnBehalfOf(Boolean canRaiseOnBehalfOf) {
    this.canRaiseOnBehalfOf = canRaiseOnBehalfOf;
    return this;
  }

   /**
   * Flag indicating if a request can be raised on behalf of another user (true) or not.
   * @return canRaiseOnBehalfOf
  **/
  @ApiModelProperty(value = "Flag indicating if a request can be raised on behalf of another user (true) or not.")
  public Boolean getCanRaiseOnBehalfOf() {
    return canRaiseOnBehalfOf;
  }

  public void setCanRaiseOnBehalfOf(Boolean canRaiseOnBehalfOf) {
    this.canRaiseOnBehalfOf = canRaiseOnBehalfOf;
  }

  public CustomerRequestCreateMetaDTO canAddRequestParticipants(Boolean canAddRequestParticipants) {
    this.canAddRequestParticipants = canAddRequestParticipants;
    return this;
  }

   /**
   * Flag indicating if participants can be added to a request (true) or not.
   * @return canAddRequestParticipants
  **/
  @ApiModelProperty(value = "Flag indicating if participants can be added to a request (true) or not.")
  public Boolean getCanAddRequestParticipants() {
    return canAddRequestParticipants;
  }

  public void setCanAddRequestParticipants(Boolean canAddRequestParticipants) {
    this.canAddRequestParticipants = canAddRequestParticipants;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerRequestCreateMetaDTO customerRequestCreateMetaDTO = (CustomerRequestCreateMetaDTO) o;
    return Objects.equals(this.requestTypeFields, customerRequestCreateMetaDTO.requestTypeFields) &&
        Objects.equals(this.canRaiseOnBehalfOf, customerRequestCreateMetaDTO.canRaiseOnBehalfOf) &&
        Objects.equals(this.canAddRequestParticipants, customerRequestCreateMetaDTO.canAddRequestParticipants);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestTypeFields, canRaiseOnBehalfOf, canAddRequestParticipants);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerRequestCreateMetaDTO {\n");
    
    sb.append("    requestTypeFields: ").append(toIndentedString(requestTypeFields)).append("\n");
    sb.append("    canRaiseOnBehalfOf: ").append(toIndentedString(canRaiseOnBehalfOf)).append("\n");
    sb.append("    canAddRequestParticipants: ").append(toIndentedString(canAddRequestParticipants)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

