/*
 * Copyright © 2011 Everit Kft. (http://www.everit.org)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Service Desk Public REST API
 * Public REST API for Jira Service Desk
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.everit.atlassian.restclient.servicedeskcloud.v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.CustomerRequestActionsDTO;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.CustomerRequestFieldValueDTO;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.CustomerRequestLinkDTO;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.CustomerRequestStatusDTO;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.DateDTO;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.PagedDTOAttachmentDTO;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.PagedDTOCommentDTO;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.PagedDTOCustomerRequestStatusDTO;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.PagedDTOSlaInformationDTO;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.PagedDTOUserDTO;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.RequestTypeDTO;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.ServiceDeskDTO;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.UserDTO;

/**
 * CustomerRequestDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-02T14:33:08.600+02:00[Europe/Prague]")
public class CustomerRequestDTO {
  @JsonProperty("issueId")
  private String issueId;

  @JsonProperty("issueKey")
  private String issueKey;

  @JsonProperty("requestTypeId")
  private String requestTypeId;

  @JsonProperty("requestType")
  private RequestTypeDTO requestType;

  @JsonProperty("serviceDeskId")
  private String serviceDeskId;

  @JsonProperty("serviceDesk")
  private ServiceDeskDTO serviceDesk;

  @JsonProperty("createdDate")
  private DateDTO createdDate;

  @JsonProperty("reporter")
  private UserDTO reporter;

  @JsonProperty("requestFieldValues")
  private List<CustomerRequestFieldValueDTO> requestFieldValues = new ArrayList<>();

  @JsonProperty("currentStatus")
  private CustomerRequestStatusDTO currentStatus;

  @JsonProperty("status")
  private PagedDTOCustomerRequestStatusDTO status;

  @JsonProperty("participants")
  private PagedDTOUserDTO participants;

  @JsonProperty("sla")
  private PagedDTOSlaInformationDTO sla;

  @JsonProperty("attachments")
  private PagedDTOAttachmentDTO attachments;

  @JsonProperty("comments")
  private PagedDTOCommentDTO comments;

  @JsonProperty("actions")
  private CustomerRequestActionsDTO actions;

  @JsonProperty("_expands")
  private List<String> expands = new ArrayList<>();

  @JsonProperty("_links")
  private CustomerRequestLinkDTO links;

  public CustomerRequestDTO issueId(String issueId) {
    this.issueId = issueId;
    return this;
  }

   /**
   * ID of the request, as the peer issue ID.
   * @return issueId
  **/
  @ApiModelProperty(value = "ID of the request, as the peer issue ID.")
  public String getIssueId() {
    return issueId;
  }

  public void setIssueId(String issueId) {
    this.issueId = issueId;
  }

  public CustomerRequestDTO issueKey(String issueKey) {
    this.issueKey = issueKey;
    return this;
  }

   /**
   * Key of the request, as the peer issue key.
   * @return issueKey
  **/
  @ApiModelProperty(value = "Key of the request, as the peer issue key.")
  public String getIssueKey() {
    return issueKey;
  }

  public void setIssueKey(String issueKey) {
    this.issueKey = issueKey;
  }

  public CustomerRequestDTO requestTypeId(String requestTypeId) {
    this.requestTypeId = requestTypeId;
    return this;
  }

   /**
   * ID of the request type for the request.
   * @return requestTypeId
  **/
  @ApiModelProperty(value = "ID of the request type for the request.")
  public String getRequestTypeId() {
    return requestTypeId;
  }

  public void setRequestTypeId(String requestTypeId) {
    this.requestTypeId = requestTypeId;
  }

  public CustomerRequestDTO requestType(RequestTypeDTO requestType) {
    this.requestType = requestType;
    return this;
  }

   /**
   * Expandable details of the request type.
   * @return requestType
  **/
  @ApiModelProperty(value = "Expandable details of the request type.")
  public RequestTypeDTO getRequestType() {
    return requestType;
  }

  public void setRequestType(RequestTypeDTO requestType) {
    this.requestType = requestType;
  }

  public CustomerRequestDTO serviceDeskId(String serviceDeskId) {
    this.serviceDeskId = serviceDeskId;
    return this;
  }

   /**
   * ID of the service desk the request belongs to.
   * @return serviceDeskId
  **/
  @ApiModelProperty(value = "ID of the service desk the request belongs to.")
  public String getServiceDeskId() {
    return serviceDeskId;
  }

  public void setServiceDeskId(String serviceDeskId) {
    this.serviceDeskId = serviceDeskId;
  }

  public CustomerRequestDTO serviceDesk(ServiceDeskDTO serviceDesk) {
    this.serviceDesk = serviceDesk;
    return this;
  }

   /**
   * Expandable details of the service desk.
   * @return serviceDesk
  **/
  @ApiModelProperty(value = "Expandable details of the service desk.")
  public ServiceDeskDTO getServiceDesk() {
    return serviceDesk;
  }

  public void setServiceDesk(ServiceDeskDTO serviceDesk) {
    this.serviceDesk = serviceDesk;
  }

  public CustomerRequestDTO createdDate(DateDTO createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Date on which the request was created.
   * @return createdDate
  **/
  @ApiModelProperty(value = "Date on which the request was created.")
  public DateDTO getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(DateDTO createdDate) {
    this.createdDate = createdDate;
  }

  public CustomerRequestDTO reporter(UserDTO reporter) {
    this.reporter = reporter;
    return this;
  }

   /**
   * Details of the customer reporting the request.
   * @return reporter
  **/
  @ApiModelProperty(value = "Details of the customer reporting the request.")
  public UserDTO getReporter() {
    return reporter;
  }

  public void setReporter(UserDTO reporter) {
    this.reporter = reporter;
  }

  public CustomerRequestDTO requestFieldValues(List<CustomerRequestFieldValueDTO> requestFieldValues) {
    this.requestFieldValues = requestFieldValues;
    return this;
  }

  public CustomerRequestDTO addRequestFieldValuesItem(CustomerRequestFieldValueDTO requestFieldValuesItem) {
    if (this.requestFieldValues == null) {
      this.requestFieldValues = new ArrayList<>();
    }
    this.requestFieldValues.add(requestFieldValuesItem);
    return this;
  }

   /**
   * JSON map of Jira field IDs and their values representing the content of the request.
   * @return requestFieldValues
  **/
  @ApiModelProperty(value = "JSON map of Jira field IDs and their values representing the content of the request.")
  public List<CustomerRequestFieldValueDTO> getRequestFieldValues() {
    return requestFieldValues;
  }

  public void setRequestFieldValues(List<CustomerRequestFieldValueDTO> requestFieldValues) {
    this.requestFieldValues = requestFieldValues;
  }

  public CustomerRequestDTO currentStatus(CustomerRequestStatusDTO currentStatus) {
    this.currentStatus = currentStatus;
    return this;
  }

   /**
   * Status of the request.
   * @return currentStatus
  **/
  @ApiModelProperty(value = "Status of the request.")
  public CustomerRequestStatusDTO getCurrentStatus() {
    return currentStatus;
  }

  public void setCurrentStatus(CustomerRequestStatusDTO currentStatus) {
    this.currentStatus = currentStatus;
  }

  public CustomerRequestDTO status(PagedDTOCustomerRequestStatusDTO status) {
    this.status = status;
    return this;
  }

   /**
   * Expandable details of the request&#39;s status history.
   * @return status
  **/
  @ApiModelProperty(value = "Expandable details of the request's status history.")
  public PagedDTOCustomerRequestStatusDTO getStatus() {
    return status;
  }

  public void setStatus(PagedDTOCustomerRequestStatusDTO status) {
    this.status = status;
  }

  public CustomerRequestDTO participants(PagedDTOUserDTO participants) {
    this.participants = participants;
    return this;
  }

   /**
   * Expandable details of the customers participating in the request.
   * @return participants
  **/
  @ApiModelProperty(value = "Expandable details of the customers participating in the request.")
  public PagedDTOUserDTO getParticipants() {
    return participants;
  }

  public void setParticipants(PagedDTOUserDTO participants) {
    this.participants = participants;
  }

  public CustomerRequestDTO sla(PagedDTOSlaInformationDTO sla) {
    this.sla = sla;
    return this;
  }

   /**
   * Expandable details of the SLAs relating to the request.
   * @return sla
  **/
  @ApiModelProperty(value = "Expandable details of the SLAs relating to the request.")
  public PagedDTOSlaInformationDTO getSla() {
    return sla;
  }

  public void setSla(PagedDTOSlaInformationDTO sla) {
    this.sla = sla;
  }

  public CustomerRequestDTO attachments(PagedDTOAttachmentDTO attachments) {
    this.attachments = attachments;
    return this;
  }

   /**
   * List of attachments included with the request.
   * @return attachments
  **/
  @ApiModelProperty(value = "List of attachments included with the request.")
  public PagedDTOAttachmentDTO getAttachments() {
    return attachments;
  }

  public void setAttachments(PagedDTOAttachmentDTO attachments) {
    this.attachments = attachments;
  }

  public CustomerRequestDTO comments(PagedDTOCommentDTO comments) {
    this.comments = comments;
    return this;
  }

   /**
   * List of comments included with the request.
   * @return comments
  **/
  @ApiModelProperty(value = "List of comments included with the request.")
  public PagedDTOCommentDTO getComments() {
    return comments;
  }

  public void setComments(PagedDTOCommentDTO comments) {
    this.comments = comments;
  }

  public CustomerRequestDTO actions(CustomerRequestActionsDTO actions) {
    this.actions = actions;
    return this;
  }

   /**
   * List of actions that the user can take on the request.
   * @return actions
  **/
  @ApiModelProperty(value = "List of actions that the user can take on the request.")
  public CustomerRequestActionsDTO getActions() {
    return actions;
  }

  public void setActions(CustomerRequestActionsDTO actions) {
    this.actions = actions;
  }

  public CustomerRequestDTO expands(List<String> expands) {
    this.expands = expands;
    return this;
  }

  public CustomerRequestDTO addExpandsItem(String expandsItem) {
    if (this.expands == null) {
      this.expands = new ArrayList<>();
    }
    this.expands.add(expandsItem);
    return this;
  }

   /**
   * List of items that can be expanded in the response by specifying the expand query parameter.
   * @return expands
  **/
  @ApiModelProperty(value = "List of items that can be expanded in the response by specifying the expand query parameter.")
  public List<String> getExpands() {
    return expands;
  }

  public void setExpands(List<String> expands) {
    this.expands = expands;
  }

  public CustomerRequestDTO links(CustomerRequestLinkDTO links) {
    this.links = links;
    return this;
  }

   /**
   * List of links associated with the request.
   * @return links
  **/
  @ApiModelProperty(value = "List of links associated with the request.")
  public CustomerRequestLinkDTO getLinks() {
    return links;
  }

  public void setLinks(CustomerRequestLinkDTO links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerRequestDTO customerRequestDTO = (CustomerRequestDTO) o;
    return Objects.equals(this.issueId, customerRequestDTO.issueId) &&
        Objects.equals(this.issueKey, customerRequestDTO.issueKey) &&
        Objects.equals(this.requestTypeId, customerRequestDTO.requestTypeId) &&
        Objects.equals(this.requestType, customerRequestDTO.requestType) &&
        Objects.equals(this.serviceDeskId, customerRequestDTO.serviceDeskId) &&
        Objects.equals(this.serviceDesk, customerRequestDTO.serviceDesk) &&
        Objects.equals(this.createdDate, customerRequestDTO.createdDate) &&
        Objects.equals(this.reporter, customerRequestDTO.reporter) &&
        Objects.equals(this.requestFieldValues, customerRequestDTO.requestFieldValues) &&
        Objects.equals(this.currentStatus, customerRequestDTO.currentStatus) &&
        Objects.equals(this.status, customerRequestDTO.status) &&
        Objects.equals(this.participants, customerRequestDTO.participants) &&
        Objects.equals(this.sla, customerRequestDTO.sla) &&
        Objects.equals(this.attachments, customerRequestDTO.attachments) &&
        Objects.equals(this.comments, customerRequestDTO.comments) &&
        Objects.equals(this.actions, customerRequestDTO.actions) &&
        Objects.equals(this.expands, customerRequestDTO.expands) &&
        Objects.equals(this.links, customerRequestDTO.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(issueId, issueKey, requestTypeId, requestType, serviceDeskId, serviceDesk, createdDate, reporter, requestFieldValues, currentStatus, status, participants, sla, attachments, comments, actions, expands, links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerRequestDTO {\n");
    
    sb.append("    issueId: ").append(toIndentedString(issueId)).append("\n");
    sb.append("    issueKey: ").append(toIndentedString(issueKey)).append("\n");
    sb.append("    requestTypeId: ").append(toIndentedString(requestTypeId)).append("\n");
    sb.append("    requestType: ").append(toIndentedString(requestType)).append("\n");
    sb.append("    serviceDeskId: ").append(toIndentedString(serviceDeskId)).append("\n");
    sb.append("    serviceDesk: ").append(toIndentedString(serviceDesk)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    reporter: ").append(toIndentedString(reporter)).append("\n");
    sb.append("    requestFieldValues: ").append(toIndentedString(requestFieldValues)).append("\n");
    sb.append("    currentStatus: ").append(toIndentedString(currentStatus)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    participants: ").append(toIndentedString(participants)).append("\n");
    sb.append("    sla: ").append(toIndentedString(sla)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    expands: ").append(toIndentedString(expands)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

