/*
 * Copyright © 2011 Everit Kft. (http://www.everit.org)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Service Desk Public REST API
 * Public REST API for Jira Service Desk
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.everit.atlassian.restclient.servicedeskcloud.v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.CustomerRequestActionDTO;

/**
 * CustomerRequestActionsDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-02T14:33:08.600+02:00[Europe/Prague]")
public class CustomerRequestActionsDTO {
  @JsonProperty("addAttachment")
  private CustomerRequestActionDTO addAttachment;

  @JsonProperty("addComment")
  private CustomerRequestActionDTO addComment;

  @JsonProperty("addParticipant")
  private CustomerRequestActionDTO addParticipant;

  @JsonProperty("removeParticipant")
  private CustomerRequestActionDTO removeParticipant;

  public CustomerRequestActionsDTO addAttachment(CustomerRequestActionDTO addAttachment) {
    this.addAttachment = addAttachment;
    return this;
  }

   /**
   * Action of adding attachments to a request.
   * @return addAttachment
  **/
  @ApiModelProperty(value = "Action of adding attachments to a request.")
  public CustomerRequestActionDTO getAddAttachment() {
    return addAttachment;
  }

  public void setAddAttachment(CustomerRequestActionDTO addAttachment) {
    this.addAttachment = addAttachment;
  }

  public CustomerRequestActionsDTO addComment(CustomerRequestActionDTO addComment) {
    this.addComment = addComment;
    return this;
  }

   /**
   * Action of adding comments to a request.
   * @return addComment
  **/
  @ApiModelProperty(value = "Action of adding comments to a request.")
  public CustomerRequestActionDTO getAddComment() {
    return addComment;
  }

  public void setAddComment(CustomerRequestActionDTO addComment) {
    this.addComment = addComment;
  }

  public CustomerRequestActionsDTO addParticipant(CustomerRequestActionDTO addParticipant) {
    this.addParticipant = addParticipant;
    return this;
  }

   /**
   * Action of adding participants to a request.
   * @return addParticipant
  **/
  @ApiModelProperty(value = "Action of adding participants to a request.")
  public CustomerRequestActionDTO getAddParticipant() {
    return addParticipant;
  }

  public void setAddParticipant(CustomerRequestActionDTO addParticipant) {
    this.addParticipant = addParticipant;
  }

  public CustomerRequestActionsDTO removeParticipant(CustomerRequestActionDTO removeParticipant) {
    this.removeParticipant = removeParticipant;
    return this;
  }

   /**
   * Action of removing participants from a request.
   * @return removeParticipant
  **/
  @ApiModelProperty(value = "Action of removing participants from a request.")
  public CustomerRequestActionDTO getRemoveParticipant() {
    return removeParticipant;
  }

  public void setRemoveParticipant(CustomerRequestActionDTO removeParticipant) {
    this.removeParticipant = removeParticipant;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerRequestActionsDTO customerRequestActionsDTO = (CustomerRequestActionsDTO) o;
    return Objects.equals(this.addAttachment, customerRequestActionsDTO.addAttachment) &&
        Objects.equals(this.addComment, customerRequestActionsDTO.addComment) &&
        Objects.equals(this.addParticipant, customerRequestActionsDTO.addParticipant) &&
        Objects.equals(this.removeParticipant, customerRequestActionsDTO.removeParticipant);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addAttachment, addComment, addParticipant, removeParticipant);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerRequestActionsDTO {\n");
    
    sb.append("    addAttachment: ").append(toIndentedString(addAttachment)).append("\n");
    sb.append("    addComment: ").append(toIndentedString(addComment)).append("\n");
    sb.append("    addParticipant: ").append(toIndentedString(addParticipant)).append("\n");
    sb.append("    removeParticipant: ").append(toIndentedString(removeParticipant)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

