/*
 * Copyright © 2011 Everit Kft. (http://www.everit.org)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Service Desk Public REST API
 * Public REST API for Jira Service Desk
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.everit.atlassian.restclient.servicedeskcloud.v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.net.URI;

/**
 * PagedLinkDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-02T14:33:08.600+02:00[Europe/Prague]")
public class PagedLinkDTO {
  @JsonProperty("self")
  private URI self;

  @JsonProperty("base")
  private URI base;

  @JsonProperty("context")
  private String context;

  @JsonProperty("next")
  private URI next;

  @JsonProperty("prev")
  private URI prev;

  public PagedLinkDTO self(URI self) {
    this.self = self;
    return this;
  }

   /**
   * REST API URL for the current page.
   * @return self
  **/
  @ApiModelProperty(value = "REST API URL for the current page.")
  public URI getSelf() {
    return self;
  }

  public void setSelf(URI self) {
    this.self = self;
  }

  public PagedLinkDTO base(URI base) {
    this.base = base;
    return this;
  }

   /**
   * Base URL for the REST API calls.
   * @return base
  **/
  @ApiModelProperty(value = "Base URL for the REST API calls.")
  public URI getBase() {
    return base;
  }

  public void setBase(URI base) {
    this.base = base;
  }

  public PagedLinkDTO context(String context) {
    this.context = context;
    return this;
  }

   /**
   * Get context
   * @return context
  **/
  @ApiModelProperty(value = "")
  public String getContext() {
    return context;
  }

  public void setContext(String context) {
    this.context = context;
  }

  public PagedLinkDTO next(URI next) {
    this.next = next;
    return this;
  }

   /**
   * REST API URL for the next page, if there is one.
   * @return next
  **/
  @ApiModelProperty(value = "REST API URL for the next page, if there is one.")
  public URI getNext() {
    return next;
  }

  public void setNext(URI next) {
    this.next = next;
  }

  public PagedLinkDTO prev(URI prev) {
    this.prev = prev;
    return this;
  }

   /**
   * REST API URL for the previous page, if there is one.
   * @return prev
  **/
  @ApiModelProperty(value = "REST API URL for the previous page, if there is one.")
  public URI getPrev() {
    return prev;
  }

  public void setPrev(URI prev) {
    this.prev = prev;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PagedLinkDTO pagedLinkDTO = (PagedLinkDTO) o;
    return Objects.equals(this.self, pagedLinkDTO.self) &&
        Objects.equals(this.base, pagedLinkDTO.base) &&
        Objects.equals(this.context, pagedLinkDTO.context) &&
        Objects.equals(this.next, pagedLinkDTO.next) &&
        Objects.equals(this.prev, pagedLinkDTO.prev);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self, base, context, next, prev);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PagedLinkDTO {\n");
    
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    base: ").append(toIndentedString(base)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("    prev: ").append(toIndentedString(prev)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

