/*
 * Copyright © 2011 Everit Kft. (http://www.everit.org)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Service Desk Public REST API
 * Public REST API for Jira Service Desk
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.everit.atlassian.restclient.servicedeskcloud.v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.CustomerRequestCreateMetaDTO;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.RequestTypeIconDTO;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.SelfLinkDTO;

/**
 * RequestTypeDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-02T14:33:08.600+02:00[Europe/Prague]")
public class RequestTypeDTO {
  @JsonProperty("id")
  private String id;

  @JsonProperty("name")
  private String name;

  @JsonProperty("description")
  private String description;

  @JsonProperty("helpText")
  private String helpText;

  @JsonProperty("issueTypeId")
  private String issueTypeId;

  @JsonProperty("serviceDeskId")
  private String serviceDeskId;

  @JsonProperty("groupIds")
  private List<String> groupIds = new ArrayList<>();

  @JsonProperty("icon")
  private RequestTypeIconDTO icon;

  @JsonProperty("fields")
  private CustomerRequestCreateMetaDTO fields;

  @JsonProperty("_expands")
  private List<String> expands = new ArrayList<>();

  @JsonProperty("_links")
  private SelfLinkDTO links;

  public RequestTypeDTO id(String id) {
    this.id = id;
    return this;
  }

   /**
   * ID for the request type.
   * @return id
  **/
  @ApiModelProperty(value = "ID for the request type.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public RequestTypeDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Short name for the request type.
   * @return name
  **/
  @ApiModelProperty(value = "Short name for the request type.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RequestTypeDTO description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of the request type.
   * @return description
  **/
  @ApiModelProperty(value = "Description of the request type.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public RequestTypeDTO helpText(String helpText) {
    this.helpText = helpText;
    return this;
  }

   /**
   * Help text for the request type.
   * @return helpText
  **/
  @ApiModelProperty(value = "Help text for the request type.")
  public String getHelpText() {
    return helpText;
  }

  public void setHelpText(String helpText) {
    this.helpText = helpText;
  }

  public RequestTypeDTO issueTypeId(String issueTypeId) {
    this.issueTypeId = issueTypeId;
    return this;
  }

   /**
   * ID of the issue type the request type is based upon.
   * @return issueTypeId
  **/
  @ApiModelProperty(value = "ID of the issue type the request type is based upon.")
  public String getIssueTypeId() {
    return issueTypeId;
  }

  public void setIssueTypeId(String issueTypeId) {
    this.issueTypeId = issueTypeId;
  }

  public RequestTypeDTO serviceDeskId(String serviceDeskId) {
    this.serviceDeskId = serviceDeskId;
    return this;
  }

   /**
   * ID of the service desk the request type belongs to.
   * @return serviceDeskId
  **/
  @ApiModelProperty(value = "ID of the service desk the request type belongs to.")
  public String getServiceDeskId() {
    return serviceDeskId;
  }

  public void setServiceDeskId(String serviceDeskId) {
    this.serviceDeskId = serviceDeskId;
  }

  public RequestTypeDTO groupIds(List<String> groupIds) {
    this.groupIds = groupIds;
    return this;
  }

  public RequestTypeDTO addGroupIdsItem(String groupIdsItem) {
    if (this.groupIds == null) {
      this.groupIds = new ArrayList<>();
    }
    this.groupIds.add(groupIdsItem);
    return this;
  }

   /**
   * List of the request type groups the request type belongs to.
   * @return groupIds
  **/
  @ApiModelProperty(value = "List of the request type groups the request type belongs to.")
  public List<String> getGroupIds() {
    return groupIds;
  }

  public void setGroupIds(List<String> groupIds) {
    this.groupIds = groupIds;
  }

  public RequestTypeDTO icon(RequestTypeIconDTO icon) {
    this.icon = icon;
    return this;
  }

   /**
   * Links to the request type&#39;s icons.
   * @return icon
  **/
  @ApiModelProperty(value = "Links to the request type's icons.")
  public RequestTypeIconDTO getIcon() {
    return icon;
  }

  public void setIcon(RequestTypeIconDTO icon) {
    this.icon = icon;
  }

  public RequestTypeDTO fields(CustomerRequestCreateMetaDTO fields) {
    this.fields = fields;
    return this;
  }

   /**
   * Fields and additional metadata for creating a request that uses the request type
   * @return fields
  **/
  @ApiModelProperty(value = "Fields and additional metadata for creating a request that uses the request type")
  public CustomerRequestCreateMetaDTO getFields() {
    return fields;
  }

  public void setFields(CustomerRequestCreateMetaDTO fields) {
    this.fields = fields;
  }

  public RequestTypeDTO expands(List<String> expands) {
    this.expands = expands;
    return this;
  }

  public RequestTypeDTO addExpandsItem(String expandsItem) {
    if (this.expands == null) {
      this.expands = new ArrayList<>();
    }
    this.expands.add(expandsItem);
    return this;
  }

   /**
   * List of items that can be expanded in the response by specifying the expand query parameter.
   * @return expands
  **/
  @ApiModelProperty(value = "List of items that can be expanded in the response by specifying the expand query parameter.")
  public List<String> getExpands() {
    return expands;
  }

  public void setExpands(List<String> expands) {
    this.expands = expands;
  }

  public RequestTypeDTO links(SelfLinkDTO links) {
    this.links = links;
    return this;
  }

   /**
   * REST API URL for the request type.
   * @return links
  **/
  @ApiModelProperty(value = "REST API URL for the request type.")
  public SelfLinkDTO getLinks() {
    return links;
  }

  public void setLinks(SelfLinkDTO links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestTypeDTO requestTypeDTO = (RequestTypeDTO) o;
    return Objects.equals(this.id, requestTypeDTO.id) &&
        Objects.equals(this.name, requestTypeDTO.name) &&
        Objects.equals(this.description, requestTypeDTO.description) &&
        Objects.equals(this.helpText, requestTypeDTO.helpText) &&
        Objects.equals(this.issueTypeId, requestTypeDTO.issueTypeId) &&
        Objects.equals(this.serviceDeskId, requestTypeDTO.serviceDeskId) &&
        Objects.equals(this.groupIds, requestTypeDTO.groupIds) &&
        Objects.equals(this.icon, requestTypeDTO.icon) &&
        Objects.equals(this.fields, requestTypeDTO.fields) &&
        Objects.equals(this.expands, requestTypeDTO.expands) &&
        Objects.equals(this.links, requestTypeDTO.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, helpText, issueTypeId, serviceDeskId, groupIds, icon, fields, expands, links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestTypeDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    helpText: ").append(toIndentedString(helpText)).append("\n");
    sb.append("    issueTypeId: ").append(toIndentedString(issueTypeId)).append("\n");
    sb.append("    serviceDeskId: ").append(toIndentedString(serviceDeskId)).append("\n");
    sb.append("    groupIds: ").append(toIndentedString(groupIds)).append("\n");
    sb.append("    icon: ").append(toIndentedString(icon)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    expands: ").append(toIndentedString(expands)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

