/*
 * Copyright © 2011 Everit Kft. (http://www.everit.org)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Service Desk Public REST API
 * Public REST API for Jira Service Desk
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.everit.atlassian.restclient.servicedeskcloud.v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * RequestTypeFieldValueDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-02T14:33:08.600+02:00[Europe/Prague]")
public class RequestTypeFieldValueDTO {
  @JsonProperty("value")
  private String value;

  @JsonProperty("label")
  private String label;

  @JsonProperty("children")
  private List<RequestTypeFieldValueDTO> children = new ArrayList<>();

  public RequestTypeFieldValueDTO value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Value of the field.
   * @return value
  **/
  @ApiModelProperty(value = "Value of the field.")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public RequestTypeFieldValueDTO label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Label for the field.
   * @return label
  **/
  @ApiModelProperty(value = "Label for the field.")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public RequestTypeFieldValueDTO children(List<RequestTypeFieldValueDTO> children) {
    this.children = children;
    return this;
  }

  public RequestTypeFieldValueDTO addChildrenItem(RequestTypeFieldValueDTO childrenItem) {
    if (this.children == null) {
      this.children = new ArrayList<>();
    }
    this.children.add(childrenItem);
    return this;
  }

   /**
   * List of child fields.
   * @return children
  **/
  @ApiModelProperty(value = "List of child fields.")
  public List<RequestTypeFieldValueDTO> getChildren() {
    return children;
  }

  public void setChildren(List<RequestTypeFieldValueDTO> children) {
    this.children = children;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestTypeFieldValueDTO requestTypeFieldValueDTO = (RequestTypeFieldValueDTO) o;
    return Objects.equals(this.value, requestTypeFieldValueDTO.value) &&
        Objects.equals(this.label, requestTypeFieldValueDTO.label) &&
        Objects.equals(this.children, requestTypeFieldValueDTO.children);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, label, children);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestTypeFieldValueDTO {\n");
    
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

