/*
 * Copyright © 2011 Everit Kft. (http://www.everit.org)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Service Desk Public REST API
 * Public REST API for Jira Service Desk
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.everit.atlassian.restclient.servicedeskcloud.v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.SelfLinkDTO;

/**
 * ServiceDeskDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-02T14:33:08.600+02:00[Europe/Prague]")
public class ServiceDeskDTO {
  @JsonProperty("id")
  private String id;

  @JsonProperty("projectId")
  private String projectId;

  @JsonProperty("projectName")
  private String projectName;

  @JsonProperty("projectKey")
  private String projectKey;

  @JsonProperty("_links")
  private SelfLinkDTO links;

  public ServiceDeskDTO id(String id) {
    this.id = id;
    return this;
  }

   /**
   * ID of the service desk.
   * @return id
  **/
  @ApiModelProperty(value = "ID of the service desk.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ServiceDeskDTO projectId(String projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * ID of the peer project for the service desk.
   * @return projectId
  **/
  @ApiModelProperty(value = "ID of the peer project for the service desk.")
  public String getProjectId() {
    return projectId;
  }

  public void setProjectId(String projectId) {
    this.projectId = projectId;
  }

  public ServiceDeskDTO projectName(String projectName) {
    this.projectName = projectName;
    return this;
  }

   /**
   * Name of the project and service desk.
   * @return projectName
  **/
  @ApiModelProperty(value = "Name of the project and service desk.")
  public String getProjectName() {
    return projectName;
  }

  public void setProjectName(String projectName) {
    this.projectName = projectName;
  }

  public ServiceDeskDTO projectKey(String projectKey) {
    this.projectKey = projectKey;
    return this;
  }

   /**
   * Key of the peer project of the service desk.
   * @return projectKey
  **/
  @ApiModelProperty(value = "Key of the peer project of the service desk.")
  public String getProjectKey() {
    return projectKey;
  }

  public void setProjectKey(String projectKey) {
    this.projectKey = projectKey;
  }

  public ServiceDeskDTO links(SelfLinkDTO links) {
    this.links = links;
    return this;
  }

   /**
   * REST API URL to the service desk.
   * @return links
  **/
  @ApiModelProperty(value = "REST API URL to the service desk.")
  public SelfLinkDTO getLinks() {
    return links;
  }

  public void setLinks(SelfLinkDTO links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceDeskDTO serviceDeskDTO = (ServiceDeskDTO) o;
    return Objects.equals(this.id, serviceDeskDTO.id) &&
        Objects.equals(this.projectId, serviceDeskDTO.projectId) &&
        Objects.equals(this.projectName, serviceDeskDTO.projectName) &&
        Objects.equals(this.projectKey, serviceDeskDTO.projectKey) &&
        Objects.equals(this.links, serviceDeskDTO.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, projectId, projectName, projectKey, links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceDeskDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    projectName: ").append(toIndentedString(projectName)).append("\n");
    sb.append("    projectKey: ").append(toIndentedString(projectKey)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

