/*
 * Copyright © 2011 Everit Kft. (http://www.everit.org)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Service Desk Public REST API
 * Public REST API for Jira Service Desk
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.everit.atlassian.restclient.servicedeskcloud.v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.SelfLinkDTO;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.SlaInformationCompletedCycleDTO;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.SlaInformationOngoingCycleDTO;

/**
 * SlaInformationDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-02T14:33:08.600+02:00[Europe/Prague]")
public class SlaInformationDTO {
  @JsonProperty("id")
  private String id;

  @JsonProperty("name")
  private String name;

  @JsonProperty("completedCycles")
  private List<SlaInformationCompletedCycleDTO> completedCycles = new ArrayList<>();

  @JsonProperty("ongoingCycle")
  private SlaInformationOngoingCycleDTO ongoingCycle;

  @JsonProperty("_links")
  private SelfLinkDTO links;

  public SlaInformationDTO id(String id) {
    this.id = id;
    return this;
  }

   /**
   * ID of the Service Level Agreement (SLA).
   * @return id
  **/
  @ApiModelProperty(value = "ID of the Service Level Agreement (SLA).")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SlaInformationDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Description of the SLA.
   * @return name
  **/
  @ApiModelProperty(value = "Description of the SLA.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SlaInformationDTO completedCycles(List<SlaInformationCompletedCycleDTO> completedCycles) {
    this.completedCycles = completedCycles;
    return this;
  }

  public SlaInformationDTO addCompletedCyclesItem(SlaInformationCompletedCycleDTO completedCyclesItem) {
    if (this.completedCycles == null) {
      this.completedCycles = new ArrayList<>();
    }
    this.completedCycles.add(completedCyclesItem);
    return this;
  }

   /**
   * List of completed cycles for the SLA.
   * @return completedCycles
  **/
  @ApiModelProperty(value = "List of completed cycles for the SLA.")
  public List<SlaInformationCompletedCycleDTO> getCompletedCycles() {
    return completedCycles;
  }

  public void setCompletedCycles(List<SlaInformationCompletedCycleDTO> completedCycles) {
    this.completedCycles = completedCycles;
  }

  public SlaInformationDTO ongoingCycle(SlaInformationOngoingCycleDTO ongoingCycle) {
    this.ongoingCycle = ongoingCycle;
    return this;
  }

   /**
   * Details of the active cycle for the SLA.
   * @return ongoingCycle
  **/
  @ApiModelProperty(value = "Details of the active cycle for the SLA.")
  public SlaInformationOngoingCycleDTO getOngoingCycle() {
    return ongoingCycle;
  }

  public void setOngoingCycle(SlaInformationOngoingCycleDTO ongoingCycle) {
    this.ongoingCycle = ongoingCycle;
  }

  public SlaInformationDTO links(SelfLinkDTO links) {
    this.links = links;
    return this;
  }

   /**
   * REST API URL for the SLA.
   * @return links
  **/
  @ApiModelProperty(value = "REST API URL for the SLA.")
  public SelfLinkDTO getLinks() {
    return links;
  }

  public void setLinks(SelfLinkDTO links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SlaInformationDTO slaInformationDTO = (SlaInformationDTO) o;
    return Objects.equals(this.id, slaInformationDTO.id) &&
        Objects.equals(this.name, slaInformationDTO.name) &&
        Objects.equals(this.completedCycles, slaInformationDTO.completedCycles) &&
        Objects.equals(this.ongoingCycle, slaInformationDTO.ongoingCycle) &&
        Objects.equals(this.links, slaInformationDTO.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, completedCycles, ongoingCycle, links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SlaInformationDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    completedCycles: ").append(toIndentedString(completedCycles)).append("\n");
    sb.append("    ongoingCycle: ").append(toIndentedString(ongoingCycle)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

