/*
 * Copyright © 2011 Everit Kft. (http://www.everit.org)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Service Desk Public REST API
 * Public REST API for Jira Service Desk
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.everit.atlassian.restclient.servicedeskcloud.v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.DateDTO;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.DurationDTO;

/**
 * SlaInformationOngoingCycleDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-02T14:33:08.600+02:00[Europe/Prague]")
public class SlaInformationOngoingCycleDTO {
  @JsonProperty("startTime")
  private DateDTO startTime;

  @JsonProperty("breachTime")
  private DateDTO breachTime;

  @JsonProperty("breached")
  private Boolean breached;

  @JsonProperty("paused")
  private Boolean paused;

  @JsonProperty("withinCalendarHours")
  private Boolean withinCalendarHours;

  @JsonProperty("goalDuration")
  private DurationDTO goalDuration;

  @JsonProperty("elapsedTime")
  private DurationDTO elapsedTime;

  @JsonProperty("remainingTime")
  private DurationDTO remainingTime;

  public SlaInformationOngoingCycleDTO startTime(DateDTO startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Time and date at which the SLA cycle started.
   * @return startTime
  **/
  @ApiModelProperty(value = "Time and date at which the SLA cycle started.")
  public DateDTO getStartTime() {
    return startTime;
  }

  public void setStartTime(DateDTO startTime) {
    this.startTime = startTime;
  }

  public SlaInformationOngoingCycleDTO breachTime(DateDTO breachTime) {
    this.breachTime = breachTime;
    return this;
  }

   /**
   * Time and date at which the SLA cycle would have breached its limit.
   * @return breachTime
  **/
  @ApiModelProperty(value = "Time and date at which the SLA cycle would have breached its limit.")
  public DateDTO getBreachTime() {
    return breachTime;
  }

  public void setBreachTime(DateDTO breachTime) {
    this.breachTime = breachTime;
  }

  public SlaInformationOngoingCycleDTO breached(Boolean breached) {
    this.breached = breached;
    return this;
  }

   /**
   * Indicates whether the SLA has been breached (true) or not (false).
   * @return breached
  **/
  @ApiModelProperty(value = "Indicates whether the SLA has been breached (true) or not (false).")
  public Boolean getBreached() {
    return breached;
  }

  public void setBreached(Boolean breached) {
    this.breached = breached;
  }

  public SlaInformationOngoingCycleDTO paused(Boolean paused) {
    this.paused = paused;
    return this;
  }

   /**
   * Indicates whether the SLA is paused (true) or not (false).
   * @return paused
  **/
  @ApiModelProperty(value = "Indicates whether the SLA is paused (true) or not (false).")
  public Boolean getPaused() {
    return paused;
  }

  public void setPaused(Boolean paused) {
    this.paused = paused;
  }

  public SlaInformationOngoingCycleDTO withinCalendarHours(Boolean withinCalendarHours) {
    this.withinCalendarHours = withinCalendarHours;
    return this;
  }

   /**
   * Indicates whether the SLA it timed during calendared working hours only (true) or not (false).
   * @return withinCalendarHours
  **/
  @ApiModelProperty(value = "Indicates whether the SLA it timed during calendared working hours only (true) or not (false).")
  public Boolean getWithinCalendarHours() {
    return withinCalendarHours;
  }

  public void setWithinCalendarHours(Boolean withinCalendarHours) {
    this.withinCalendarHours = withinCalendarHours;
  }

  public SlaInformationOngoingCycleDTO goalDuration(DurationDTO goalDuration) {
    this.goalDuration = goalDuration;
    return this;
  }

   /**
   * Duration within which the service should be completed.
   * @return goalDuration
  **/
  @ApiModelProperty(value = "Duration within which the service should be completed.")
  public DurationDTO getGoalDuration() {
    return goalDuration;
  }

  public void setGoalDuration(DurationDTO goalDuration) {
    this.goalDuration = goalDuration;
  }

  public SlaInformationOngoingCycleDTO elapsedTime(DurationDTO elapsedTime) {
    this.elapsedTime = elapsedTime;
    return this;
  }

   /**
   * Duration of the service.
   * @return elapsedTime
  **/
  @ApiModelProperty(value = "Duration of the service.")
  public DurationDTO getElapsedTime() {
    return elapsedTime;
  }

  public void setElapsedTime(DurationDTO elapsedTime) {
    this.elapsedTime = elapsedTime;
  }

  public SlaInformationOngoingCycleDTO remainingTime(DurationDTO remainingTime) {
    this.remainingTime = remainingTime;
    return this;
  }

   /**
   * Duration remaining in which to complete the service.
   * @return remainingTime
  **/
  @ApiModelProperty(value = "Duration remaining in which to complete the service.")
  public DurationDTO getRemainingTime() {
    return remainingTime;
  }

  public void setRemainingTime(DurationDTO remainingTime) {
    this.remainingTime = remainingTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SlaInformationOngoingCycleDTO slaInformationOngoingCycleDTO = (SlaInformationOngoingCycleDTO) o;
    return Objects.equals(this.startTime, slaInformationOngoingCycleDTO.startTime) &&
        Objects.equals(this.breachTime, slaInformationOngoingCycleDTO.breachTime) &&
        Objects.equals(this.breached, slaInformationOngoingCycleDTO.breached) &&
        Objects.equals(this.paused, slaInformationOngoingCycleDTO.paused) &&
        Objects.equals(this.withinCalendarHours, slaInformationOngoingCycleDTO.withinCalendarHours) &&
        Objects.equals(this.goalDuration, slaInformationOngoingCycleDTO.goalDuration) &&
        Objects.equals(this.elapsedTime, slaInformationOngoingCycleDTO.elapsedTime) &&
        Objects.equals(this.remainingTime, slaInformationOngoingCycleDTO.remainingTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startTime, breachTime, breached, paused, withinCalendarHours, goalDuration, elapsedTime, remainingTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SlaInformationOngoingCycleDTO {\n");
    
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    breachTime: ").append(toIndentedString(breachTime)).append("\n");
    sb.append("    breached: ").append(toIndentedString(breached)).append("\n");
    sb.append("    paused: ").append(toIndentedString(paused)).append("\n");
    sb.append("    withinCalendarHours: ").append(toIndentedString(withinCalendarHours)).append("\n");
    sb.append("    goalDuration: ").append(toIndentedString(goalDuration)).append("\n");
    sb.append("    elapsedTime: ").append(toIndentedString(elapsedTime)).append("\n");
    sb.append("    remainingTime: ").append(toIndentedString(remainingTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

