/*
 * Copyright © 2011 Everit Kft. (http://www.everit.org)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Service Desk Public REST API
 * Public REST API for Jira Service Desk
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.everit.atlassian.restclient.servicedeskcloud.v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.DateDTO;
import org.everit.atlassian.restclient.servicedeskcloud.v3.model.SelfLinkDTO;

/**
 * SoftwareInfoDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-02T14:33:08.600+02:00[Europe/Prague]")
public class SoftwareInfoDTO {
  @JsonProperty("version")
  private String version;

  @JsonProperty("platformVersion")
  private String platformVersion;

  @JsonProperty("buildDate")
  private DateDTO buildDate;

  @JsonProperty("buildChangeSet")
  private String buildChangeSet;

  @JsonProperty("isLicensedForUse")
  private Boolean isLicensedForUse;

  @JsonProperty("_links")
  private SelfLinkDTO links;

  public SoftwareInfoDTO version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Jira Service Desk version.
   * @return version
  **/
  @ApiModelProperty(value = "Jira Service Desk version.")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public SoftwareInfoDTO platformVersion(String platformVersion) {
    this.platformVersion = platformVersion;
    return this;
  }

   /**
   * Jira Platform version upon which Service Desk is based.
   * @return platformVersion
  **/
  @ApiModelProperty(value = "Jira Platform version upon which Service Desk is based.")
  public String getPlatformVersion() {
    return platformVersion;
  }

  public void setPlatformVersion(String platformVersion) {
    this.platformVersion = platformVersion;
  }

  public SoftwareInfoDTO buildDate(DateDTO buildDate) {
    this.buildDate = buildDate;
    return this;
  }

   /**
   * Date of the current build.
   * @return buildDate
  **/
  @ApiModelProperty(value = "Date of the current build.")
  public DateDTO getBuildDate() {
    return buildDate;
  }

  public void setBuildDate(DateDTO buildDate) {
    this.buildDate = buildDate;
  }

  public SoftwareInfoDTO buildChangeSet(String buildChangeSet) {
    this.buildChangeSet = buildChangeSet;
    return this;
  }

   /**
   * Reference of the change set included in the build.
   * @return buildChangeSet
  **/
  @ApiModelProperty(value = "Reference of the change set included in the build.")
  public String getBuildChangeSet() {
    return buildChangeSet;
  }

  public void setBuildChangeSet(String buildChangeSet) {
    this.buildChangeSet = buildChangeSet;
  }

  public SoftwareInfoDTO isLicensedForUse(Boolean isLicensedForUse) {
    this.isLicensedForUse = isLicensedForUse;
    return this;
  }

   /**
   * Indicates whether the instance is licensed (true) or not (false).
   * @return isLicensedForUse
  **/
  @ApiModelProperty(value = "Indicates whether the instance is licensed (true) or not (false).")
  public Boolean getIsLicensedForUse() {
    return isLicensedForUse;
  }

  public void setIsLicensedForUse(Boolean isLicensedForUse) {
    this.isLicensedForUse = isLicensedForUse;
  }

  public SoftwareInfoDTO links(SelfLinkDTO links) {
    this.links = links;
    return this;
  }

   /**
   * REST API URL of the instance.
   * @return links
  **/
  @ApiModelProperty(value = "REST API URL of the instance.")
  public SelfLinkDTO getLinks() {
    return links;
  }

  public void setLinks(SelfLinkDTO links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SoftwareInfoDTO softwareInfoDTO = (SoftwareInfoDTO) o;
    return Objects.equals(this.version, softwareInfoDTO.version) &&
        Objects.equals(this.platformVersion, softwareInfoDTO.platformVersion) &&
        Objects.equals(this.buildDate, softwareInfoDTO.buildDate) &&
        Objects.equals(this.buildChangeSet, softwareInfoDTO.buildChangeSet) &&
        Objects.equals(this.isLicensedForUse, softwareInfoDTO.isLicensedForUse) &&
        Objects.equals(this.links, softwareInfoDTO.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, platformVersion, buildDate, buildChangeSet, isLicensedForUse, links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SoftwareInfoDTO {\n");
    
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    platformVersion: ").append(toIndentedString(platformVersion)).append("\n");
    sb.append("    buildDate: ").append(toIndentedString(buildDate)).append("\n");
    sb.append("    buildChangeSet: ").append(toIndentedString(buildChangeSet)).append("\n");
    sb.append("    isLicensedForUse: ").append(toIndentedString(isLicensedForUse)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

