/*
 * Copyright © 2011 Everit Kft. (http://www.everit.org)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Service Desk Public REST API
 * Public REST API for Jira Service Desk
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.everit.atlassian.restclient.servicedeskcloud.v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.net.URI;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * UserLinkDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-02T14:33:08.600+02:00[Europe/Prague]")
public class UserLinkDTO {
  @JsonProperty("self")
  private URI self;

  @JsonProperty("jiraRest")
  private URI jiraRest;

  @JsonProperty("avatarUrls")
  private Map<String, String> avatarUrls = new HashMap<>();

  public UserLinkDTO self(URI self) {
    this.self = self;
    return this;
  }

   /**
   * Get self
   * @return self
  **/
  @ApiModelProperty(value = "")
  public URI getSelf() {
    return self;
  }

  public void setSelf(URI self) {
    this.self = self;
  }

  public UserLinkDTO jiraRest(URI jiraRest) {
    this.jiraRest = jiraRest;
    return this;
  }

   /**
   * REST API URL for the customer.
   * @return jiraRest
  **/
  @ApiModelProperty(value = "REST API URL for the customer.")
  public URI getJiraRest() {
    return jiraRest;
  }

  public void setJiraRest(URI jiraRest) {
    this.jiraRest = jiraRest;
  }

  public UserLinkDTO avatarUrls(Map<String, String> avatarUrls) {
    this.avatarUrls = avatarUrls;
    return this;
  }

  public UserLinkDTO putAvatarUrlsItem(String key, String avatarUrlsItem) {
    if (this.avatarUrls == null) {
      this.avatarUrls = new HashMap<>();
    }
    this.avatarUrls.put(key, avatarUrlsItem);
    return this;
  }

   /**
   * Links to the various sizes of the customer&#39;s avatar. Note that this property is deprecated, and will be removed in future versions.
   * @return avatarUrls
  **/
  @ApiModelProperty(value = "Links to the various sizes of the customer's avatar. Note that this property is deprecated, and will be removed in future versions.")
  public Map<String, String> getAvatarUrls() {
    return avatarUrls;
  }

  public void setAvatarUrls(Map<String, String> avatarUrls) {
    this.avatarUrls = avatarUrls;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserLinkDTO userLinkDTO = (UserLinkDTO) o;
    return Objects.equals(this.self, userLinkDTO.self) &&
        Objects.equals(this.jiraRest, userLinkDTO.jiraRest) &&
        Objects.equals(this.avatarUrls, userLinkDTO.avatarUrls);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self, jiraRest, avatarUrls);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserLinkDTO {\n");
    
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    jiraRest: ").append(toIndentedString(jiraRest)).append("\n");
    sb.append("    avatarUrls: ").append(toIndentedString(avatarUrls)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

